name: AWS Assume Role

on: push

jobs:
  aws-assume-role:
    runs-on: ubuntu-latest
    steps:
      - name: Identity Check
        run: |
          echo "${{ secrets.AWS_ASSUME_ROLE_ARN }}" >> secret.txt
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" >> secret.txt
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> secret.txt
          ls -al

      - name: Assume Role
        uses: nordcloud/aws-assume-role@master
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: -r ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        # uses: abatilo/aws-assume-role-action@v1.0.0
        # env:
        #   # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        #   ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        #   ROLE_SESSION_NAME: testing
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   DURATION_SECONDS: 120
          
      - name: Identity Check
        run: |
          aws sts get-caller-identity

      - name: Show S3 Bucket List
        run: |
          aws s3 ls
